import type { Metadata } from 'next'
import { Comic_Neue } from 'next/font/google'
import './globals.css'

const font = Comic_Neue({
  subsets: ["latin"],
  weight: ["700"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
